name: Vercel-Deployment

# Run this workflow every time a new commit pushed to your repository
on: 
  workflow_dispatch:
    inputs:
      panelId:
        description: 'Panel Id of Flexpanel'     
        required: true
      versionId:
        description: 'Published Version of the Panel'  
        required: true
      vercelToken:
        description: 'Access Token of the Deployed Vercel Account'
        required: true

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  vercel-deployment:
    # Name the Job
    name: Deploy the flexpanel builder to Vercel
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      #Create vercel.json file to configure the deployment
      - name: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "vercel.json"
          json: '{ "name": ${{ github.event.inputs.panelId }}-${{ github.event.inputs.versionId }} }'

      # Runs the Super-Linter action
      - name: Vercel Action
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ github.event.inputs.vercelToken }}
          vercel-args: '--confirm'