name: Vercel-Deployment

# Run this workflow every time a new commit pushed to your repository
on: 
  workflow_dispatch:
    inputs:
      vercelJSON:
        description: 'JSON Configuration for the Vercel Project'     
        required: true
      vercelToken:
        description: 'Access Token of the Vercel Account'
        required: true
      panelID:
        description: 'Panel Id of the Deployment'
        required: true
      versionID:
        description: 'Version Id of the Deployment'
        required: true

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  vercel-deployment:
    # Name the Job
    name: Deploy the flexpanel builder to Vercel
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Create vercel.json file to configure the deployment
      - name: Create JSON
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "vercel.json"
          json: ${{ github.event.inputs.vercelJSON }}

      # Runs the Super-Linter action
      - name: Vercel Action
        uses: amondnet/vercel-action@v20.0.0
        env:
            PANEL_ID: ${{ github.event.inputs.panelID }}
            VERSION_ID: ${{ github.event.inputs.versionID }}
        with:
          vercel-token: ${{ github.event.inputs.vercelToken }}
          vercel-args: '--confirm'