name: Vercel-Deployment

# Run this workflow every time a new commit pushed to your repository
on: 
  workflow_dispatch:
    inputs:
      # vercelJSON:
      #   description: 'JSON Configuration for the Vercel Project'     
      #   required: true
      vercelToken:
        description: 'Access Token of the Vercel Account'
        required: true
      deploymentID:
        description: 'Deployment ID of the Build'
        required: true
      panelID:
        description: 'Panel Id of the Deployment'
        required: true
      versionID:
        description: 'Version Id of the Deployment'
        required: true
      organizationID:
        description: 'Organization ID of this Vercel Account'
        required: true
      projectID:
        description: 'Project ID of the Deployment'
        required: true

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  vercel-deployment:
    # Name the Job
    name: Deploy the flexpanel builder to Vercel
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Webhook Status Update
      - name: Invoke Deployment Hook (Build Start)
        uses: joelwmale/webhook-action@master
        with:
          url: "https://n2d37ssk5m.execute-api.us-east-1.amazonaws.com/default/flexpanelwebhookdeploy-dev"
          headers: '{ "x-api-key": "${{ secrets.AWS_WEBHOOK_API_KEY }}" }'
          body: '{"buildEvent": "deployment", "deploymentID": "${{ github.event.inputs.deploymentID }}", "status" : "buildStart" }'

      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Create vercel.json file to configure the deployment
      # {"name":"a75e23a4-8523-4932-bae2-471566222edd","build":{"env":{"PANEL_ID":"a75e23a4-8523-4932-bae2-471566222edd","VERSION_ID":"5ffc447b-703e-4032-bb26-570987ad4ad8"}}}
      # - name: Create JSON
      #   uses: jsdaniell/create-json@1.1.2
      #   with:
      #     name: "vercel.json"
      #     # json: ${{ github.event.inputs.vercelJSON }}
      #     json: '{ "name" : "a75e23a4-8523-4932-bae2-471566222edd" }'

      # # Webhook Status Update
      - name: Invoke Deployment Hook (Deploy Start)
        uses: joelwmale/webhook-action@master
        with:
          url: "https://n2d37ssk5m.execute-api.us-east-1.amazonaws.com/default/flexpanelwebhookdeploy-dev"
          headers: '{ "x-api-key": "${{ secrets.AWS_WEBHOOK_API_KEY }}" }'
          body: '{"buildEvent": "deployment", "deploymentID": "${{ github.event.inputs.deploymentID }}", "status" : "deployVercelStart" }'

      # Runs the Super-Linter action
      - name: Vercel Action
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ github.event.inputs.vercelToken }}
          vercel-org-id: ${{ github.event.inputs.organizationID }}
          vercel-project-id: ${{ github.event.inputs.projectID }}
          alias-domains: |
            ${{ github.event.inputs.deploymentID }}
          vercel-args: '--prod --confirm --build-env GRAPHQL_ENDPOINT=${{ secrets.GRAPHQL_ENDPOINT }} --build-env GRAPHQL_API_KEY=${{ secrets.GRAPHQL_API_KEY }} --build-env PANEL_ID=${{ github.event.inputs.panelID }} --build-env VERSION_ID=${{ github.event.inputs.versionID }} '

      # Webhook Status Update
      - name: Invoke Deployment Hook (Deploy Success)
        if: ${{ success() }}
        uses: joelwmale/webhook-action@master
        with:
          url: "https://n2d37ssk5m.execute-api.us-east-1.amazonaws.com/default/flexpanelwebhookdeploy-dev"
          headers: '{ "x-api-key": "${{ secrets.AWS_WEBHOOK_API_KEY }}" }'
          body: '{"buildEvent": "deployment", "deploymentID": "${{ github.event.inputs.deploymentID }}", "status" : "deployVercelSuccess" }'

      # # Webhook Status Update
      - name: Invoke Deployment Hook (Deploy Fail)
        if: ${{ failure() }}
        uses: joelwmale/webhook-action@master
        with:
          url: "https://n2d37ssk5m.execute-api.us-east-1.amazonaws.com/default/flexpanelwebhookdeploy-dev"
          headers: '{ "x-api-key": "${{ secrets.AWS_WEBHOOK_API_KEY }}" }'
          body: '{"buildEvent": "deployment", "deploymentID": "${{ github.event.inputs.deploymentID }}", "status" : "deployVercelFail" }'